# Generated by Django 2.1.2 on 2018-10-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181011_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
