# Generated by Django 2.1.4 on 2019-01-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181228_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
    ]
