# Generated by Django 2.0.4 on 2018-04-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('pin_code', models.CharField(max_length=255, verbose_name='PINコード')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='years.Year')),
            ],
            options={
                'ordering': ['name', '-year__year'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'year')},
        ),
    ]
