# Generated by Django 2.1.4 on 2019-01-03 05:21

from django.db import migrations, models
import django.db.models.deletion

# TODO: マイグレーション時に存在しなければ自動でグループを作る．


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('courses', '0003_auto_20190101_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admin_user_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='auth.Group'),
        ),
    ]
