# Generated by Django 2.1.5 on 2019-01-06 07:10

from django.db import migrations, models
import django.db.models.deletion


def make_config(apps, schema_editor):
    """まだ設定が作成されていない場合，デフォルトの設定を生成する"""
    Course = apps.get_model('courses', 'Course')
    Config = apps.get_model('courses', 'Config')
    db_alias = schema_editor.connection.alias
    for course in Course.objects.using(db_alias).all():
        config = Config()
        course.config = config
        course.save()
        config.save()


def delete_config(apps, schema_editor):
    """ロールバック時に生成された設定を破棄"""
    Course = apps.get_model('courses', 'Course')
    db_alias = schema_editor.connection.alias
    for course in Course.objects.using(db_alias).all():
        try:
            course.config.delete()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_admin_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_gpa', models.BooleanField(default=False, verbose_name='GAPを表示する')),
                ('show_username', models.BooleanField(default=False, verbose_name='ユーザ名を表示する')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='courses.Course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '表示設定',
                'verbose_name_plural': '表示設定',
            },
        ),
        migrations.RunPython(make_config, delete_config),
    ]
