# Generated by Django 2.1.5 on 2019-01-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='研究室名')),
                ('capacity', models.IntegerField(default=0, verbose_name='許容人数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='courses.Course')),
            ],
            options={
                'verbose_name': '研究室',
                'verbose_name_plural': '研究室',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('name', 'course')},
        ),
    ]
