# Generated by Django 2.1.5 on 2019-01-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190106_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Lab', verbose_name='研究室'),
        ),
    ]
