# Generated by Django 2.1.2 on 2018-10-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='研究室名')),
                ('capacity', models.IntegerField(default=0, verbose_name='定員')),
            ],
            options={
                'ordering': ['name', '-course__year__year'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='志望順位')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Lab', verbose_name='研究室')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
