# Generated by Django 2.1.2 on 2018-10-08 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='courses.Course', verbose_name='課程'),
        ),
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('lab', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('name', 'course')},
        ),
    ]
