# Generated by Django 2.0.4 on 2018-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='年度')),
            ],
            options={
                'verbose_name': '年度',
                'verbose_name_plural': '年度',
                'ordering': ['year'],
            },
        ),
    ]
